#####
name: Copy DevOps Workflow

on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
            
      # 將repo 過濾出來
      - name: Checkout BE-repo        
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
  RUN_T:
    runs-one: ubuntu-latest
    steps:
      - name: echo "HAHAHAHAHA"
        run: |
          echo "HAHAHAHAHAHA"     
