#####
name: Copy DevOps Workflow

on:
  workflow_call:
    secrets:
      AWS_ID:
        required: true
      AWS_KEY:
        required: true 

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
            
      # 將repo 過濾出來
      - name: Checkout BE-repo        
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

  RUN_T:
    runs-on: ubuntu-latest
    
    steps:
    - name: echo variabele
      run: |
        echo "${{ secrets.AWS_ID }}"
        echo "${{ secrets.AWS_KEY }}"
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ID }}
        aws-secret-access-key: ${{ secrets.AWS_KEY }}
        aws-region: ap-northeast-1

    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1
      with:
        project-name: github_api

  RUN_C:
    runs-on: ubuntu-latest
    # needs: RUN_T
    steps:
      - name: echo "HAHAHAHAHA"
        run: |
          echo "HAHAHAHAHAHA"     
